# Generated by Django 2.1.5 on 2019-04-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="blog", options={"ordering": ["post_date"]}),
        migrations.RenameField(
            model_name="blog", old_name="post_data", new_name="post_date"
        ),
    ]
