# Generated by Django 2.1.5 on 2019-04-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="blogcomment",
            options={
                "ordering": ["post_date"],
                "permissions": (("can_add_comment", "Add comment to blog"),),
            },
        )
    ]
