# Generated by Django 2.1.5 on 2019-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_auto_20190425_1349")]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["post_date"],
                "permissions": (("can_add_comment", "Add comment to blog"),),
            },
        ),
        migrations.AlterModelOptions(
            name="blogcomment", options={"ordering": ["post_date"]}
        ),
    ]
