# Generated by Django 2.1.5 on 2019-04-23 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_auto_20190423_1937")]

    operations = [
        migrations.RenameField(
            model_name="blog", old_name="author", new_name="blogger"
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.CharField(
                help_text="Enter your blog text here", max_length=2000
            ),
        ),
        migrations.AlterField(
            model_name="blogger",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
