# Generated by Django 2.1.5 on 2019-04-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0003_auto_20190423_2115")]

    operations = [
        migrations.RemoveField(model_name="blogcomment", name="blog"),
        migrations.RemoveField(model_name="blogcomment", name="blogger"),
        migrations.DeleteModel(name="BlogComment"),
    ]
