#comment spring:datasource will use embedded H2 database
#spring:
#    datasource:
#        password: uroot
#        url: jdbc:mysql://localhost:3306/titanic
#        username: uroot
#    jpa:
#        hibernate:
#            ddl-auto: none
# jpa:hibernate:ddl-auto: create will drop the existing table